// playgrounds/react-app/src/App.tsx
import { useState } from 'react'
import './App.css'
import {
  Lit101Appbar,
  Lit101Theme,
  Lit101Navitem,
  Lit101Applayout,
  Lit101Nav,
  Lit101Card,
  Lit101Container,
  Lit101Cardbody,
} from '@lit101/components/react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <Lit101Theme>
        <Lit101Applayout>
          <Lit101Nav slot="sidebar">
            <div slot="logo">
              Logo
            </div>
            <Lit101Navitem active>
              Hello
            </Lit101Navitem>
          </Lit101Nav>
          <Lit101Appbar>Testi</Lit101Appbar>
          <Lit101Container>
            <Lit101Card>
              <Lit101Cardbody>
                <a href="https://vitejs.dev" target="_blank">
                  {/* <img src={viteLogo} className="logo" alt="Vite logo" /> */}
                </a>
                <a href="https://reactjs.org" target="_blank">
                  {/* <img src={reactLogo} className="logo react" alt="React logo" /> */}
                </a>
              </Lit101Cardbody>
            </Lit101Card>
            <Lit101Card>
              <Lit101Cardbody>
                <h1>Vite + React2</h1>
                <div className="card">
                  <button onClick={() => setCount((count) => count + 1)}>
                    count is {count}
                  </button>
                  <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                  </p>
                </div>
                <p className="read-the-docs">
                  Click on the Vite and React logos to learn more
                </p>
              </Lit101Cardbody>
            </Lit101Card>
          </Lit101Container>
        </Lit101Applayout>
      </Lit101Theme>
    </div>
  )
}

export default App

// playgrounds/lit-app/src/lit-app.ts
import { LitElement, css, html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';

import viteLogo from '/vite.svg'


/**
 * An example element.
 *
 * @slot - This element has a slot
 * @csspart button - The button
 */
@customElement( 'lit-app' )
export class LitApp extends LitElement {

  @property({ type: Number }) count = 0

  render() {
    return html`
      <lit101-theme>
        <lit101-applayout>
          <lit101-nav slot="sidebar">
            <div slot="logo">
              Logo
            </div>
            <lit101-navitem active>
              Affe
            </lit101-navitem>
          </lit101-nav>
          <lit101-container>
            <lit101-appbar>
            </lit101-appbar>
            <lit101-card>
              <lit101-cardbody>
                <a href="https://vitejs.dev" target="_blank">
                  <img src=${ viteLogo } class="logo" alt="Vite logo" />
                </a>
                <a href="https://lit.dev" target="_blank">
                  <img src=${ litLogo } class="logo lit" alt="Lit logo" />
                </a>
              </lit101-cardbody>
            </lit101-card>
            <lit101-card>
              <lit101-cardbody>
                <button @click=${this._onClick} part="button">
                  count is ${this.count}
                </button>
                <p class="read-the-docs">Click on the Vite and Lit logos to learn more</p>
              </lit101-cardbody>
            </lit101-card>
          </lit101-container>
        </lit101-applayout>
      </lit101-theme>
    `
  }

  private _onClick() {
    this.count++
  }

  static styles = css`
    :host {
    }
  `
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-app': LitApp,
  }
}
